// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package admin

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *AdminLoginReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_AdminLoginReq[number], err)
}

func (x *AdminLoginReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Account, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AdminLoginReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Password, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AdminLoginResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_AdminLoginResp[number], err)
}

func (x *AdminLoginResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.UserId, offset, err = fastpb.ReadUint32(buf, _type)
	return offset, err
}

func (x *AdminRegisterReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_AdminRegisterReq[number], err)
}

func (x *AdminRegisterReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Name, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AdminRegisterReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Password, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AdminRegisterReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.Account, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AdminRegisterResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_AdminRegisterResp[number], err)
}

func (x *AdminRegisterResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.AdminId, offset, err = fastpb.ReadUint32(buf, _type)
	return offset, err
}

func (x *AdminRegisterResp) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Account, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AdminLoginReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *AdminLoginReq) fastWriteField1(buf []byte) (offset int) {
	if x.Account == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetAccount())
	return offset
}

func (x *AdminLoginReq) fastWriteField2(buf []byte) (offset int) {
	if x.Password == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetPassword())
	return offset
}

func (x *AdminLoginResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *AdminLoginResp) fastWriteField1(buf []byte) (offset int) {
	if x.UserId == 0 {
		return offset
	}
	offset += fastpb.WriteUint32(buf[offset:], 1, x.GetUserId())
	return offset
}

func (x *AdminRegisterReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *AdminRegisterReq) fastWriteField1(buf []byte) (offset int) {
	if x.Name == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetName())
	return offset
}

func (x *AdminRegisterReq) fastWriteField2(buf []byte) (offset int) {
	if x.Password == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetPassword())
	return offset
}

func (x *AdminRegisterReq) fastWriteField3(buf []byte) (offset int) {
	if x.Account == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetAccount())
	return offset
}

func (x *AdminRegisterResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *AdminRegisterResp) fastWriteField1(buf []byte) (offset int) {
	if x.AdminId == 0 {
		return offset
	}
	offset += fastpb.WriteUint32(buf[offset:], 1, x.GetAdminId())
	return offset
}

func (x *AdminRegisterResp) fastWriteField2(buf []byte) (offset int) {
	if x.Account == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetAccount())
	return offset
}

func (x *AdminLoginReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *AdminLoginReq) sizeField1() (n int) {
	if x.Account == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetAccount())
	return n
}

func (x *AdminLoginReq) sizeField2() (n int) {
	if x.Password == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetPassword())
	return n
}

func (x *AdminLoginResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *AdminLoginResp) sizeField1() (n int) {
	if x.UserId == 0 {
		return n
	}
	n += fastpb.SizeUint32(1, x.GetUserId())
	return n
}

func (x *AdminRegisterReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *AdminRegisterReq) sizeField1() (n int) {
	if x.Name == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetName())
	return n
}

func (x *AdminRegisterReq) sizeField2() (n int) {
	if x.Password == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetPassword())
	return n
}

func (x *AdminRegisterReq) sizeField3() (n int) {
	if x.Account == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetAccount())
	return n
}

func (x *AdminRegisterResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *AdminRegisterResp) sizeField1() (n int) {
	if x.AdminId == 0 {
		return n
	}
	n += fastpb.SizeUint32(1, x.GetAdminId())
	return n
}

func (x *AdminRegisterResp) sizeField2() (n int) {
	if x.Account == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetAccount())
	return n
}

var fieldIDToName_AdminLoginReq = map[int32]string{
	1: "Account",
	2: "Password",
}

var fieldIDToName_AdminLoginResp = map[int32]string{
	1: "UserId",
}

var fieldIDToName_AdminRegisterReq = map[int32]string{
	1: "Name",
	2: "Password",
	3: "Account",
}

var fieldIDToName_AdminRegisterResp = map[int32]string{
	1: "AdminId",
	2: "Account",
}
