image: golang:latest

stages:
  - test
  - build
  - deploy

format:
  stage: test
  script:
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - mkdir -p target
    - go build -o target ./...
  artifacts:
    paths:
      - target

deploy:
  stage: deploy
  script: echo "deploy stage currently unused"
  environment: production
