// Code generated by Kitex v0.9.1. DO NOT EDIT.

package merchantservice

import (
	"context"
	merchant "delivery-backend/rpc_gen/kitex_gen/user/merchant"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"MerchantRegister": kitex.NewMethodInfo(
		merchantRegisterHandler,
		newMerchantRegisterArgs,
		newMerchantRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"MerchantLogin": kitex.NewMethodInfo(
		merchantLoginHandler,
		newMerchantLoginArgs,
		newMerchantLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	merchantServiceServiceInfo                = NewServiceInfo()
	merchantServiceServiceInfoForClient       = NewServiceInfoForClient()
	merchantServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return merchantServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return merchantServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return merchantServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "MerchantService"
	handlerType := (*merchant.MerchantService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user.merchant",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func merchantRegisterHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(merchant.MerchantRegisterReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(merchant.MerchantService).MerchantRegister(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *MerchantRegisterArgs:
		success, err := handler.(merchant.MerchantService).MerchantRegister(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*MerchantRegisterResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newMerchantRegisterArgs() interface{} {
	return &MerchantRegisterArgs{}
}

func newMerchantRegisterResult() interface{} {
	return &MerchantRegisterResult{}
}

type MerchantRegisterArgs struct {
	Req *merchant.MerchantRegisterReq
}

func (p *MerchantRegisterArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(merchant.MerchantRegisterReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *MerchantRegisterArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *MerchantRegisterArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *MerchantRegisterArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *MerchantRegisterArgs) Unmarshal(in []byte) error {
	msg := new(merchant.MerchantRegisterReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var MerchantRegisterArgs_Req_DEFAULT *merchant.MerchantRegisterReq

func (p *MerchantRegisterArgs) GetReq() *merchant.MerchantRegisterReq {
	if !p.IsSetReq() {
		return MerchantRegisterArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *MerchantRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MerchantRegisterArgs) GetFirstArgument() interface{} {
	return p.Req
}

type MerchantRegisterResult struct {
	Success *merchant.MerchantRegisterResp
}

var MerchantRegisterResult_Success_DEFAULT *merchant.MerchantRegisterResp

func (p *MerchantRegisterResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(merchant.MerchantRegisterResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *MerchantRegisterResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *MerchantRegisterResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *MerchantRegisterResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *MerchantRegisterResult) Unmarshal(in []byte) error {
	msg := new(merchant.MerchantRegisterResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *MerchantRegisterResult) GetSuccess() *merchant.MerchantRegisterResp {
	if !p.IsSetSuccess() {
		return MerchantRegisterResult_Success_DEFAULT
	}
	return p.Success
}

func (p *MerchantRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*merchant.MerchantRegisterResp)
}

func (p *MerchantRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MerchantRegisterResult) GetResult() interface{} {
	return p.Success
}

func merchantLoginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(merchant.MerchantLoginReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(merchant.MerchantService).MerchantLogin(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *MerchantLoginArgs:
		success, err := handler.(merchant.MerchantService).MerchantLogin(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*MerchantLoginResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newMerchantLoginArgs() interface{} {
	return &MerchantLoginArgs{}
}

func newMerchantLoginResult() interface{} {
	return &MerchantLoginResult{}
}

type MerchantLoginArgs struct {
	Req *merchant.MerchantLoginReq
}

func (p *MerchantLoginArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(merchant.MerchantLoginReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *MerchantLoginArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *MerchantLoginArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *MerchantLoginArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *MerchantLoginArgs) Unmarshal(in []byte) error {
	msg := new(merchant.MerchantLoginReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var MerchantLoginArgs_Req_DEFAULT *merchant.MerchantLoginReq

func (p *MerchantLoginArgs) GetReq() *merchant.MerchantLoginReq {
	if !p.IsSetReq() {
		return MerchantLoginArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *MerchantLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MerchantLoginArgs) GetFirstArgument() interface{} {
	return p.Req
}

type MerchantLoginResult struct {
	Success *merchant.MerchantLoginResp
}

var MerchantLoginResult_Success_DEFAULT *merchant.MerchantLoginResp

func (p *MerchantLoginResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(merchant.MerchantLoginResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *MerchantLoginResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *MerchantLoginResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *MerchantLoginResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *MerchantLoginResult) Unmarshal(in []byte) error {
	msg := new(merchant.MerchantLoginResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *MerchantLoginResult) GetSuccess() *merchant.MerchantLoginResp {
	if !p.IsSetSuccess() {
		return MerchantLoginResult_Success_DEFAULT
	}
	return p.Success
}

func (p *MerchantLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*merchant.MerchantLoginResp)
}

func (p *MerchantLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MerchantLoginResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) MerchantRegister(ctx context.Context, Req *merchant.MerchantRegisterReq) (r *merchant.MerchantRegisterResp, err error) {
	var _args MerchantRegisterArgs
	_args.Req = Req
	var _result MerchantRegisterResult
	if err = p.c.Call(ctx, "MerchantRegister", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MerchantLogin(ctx context.Context, Req *merchant.MerchantLoginReq) (r *merchant.MerchantLoginResp, err error) {
	var _args MerchantLoginArgs
	_args.Req = Req
	var _result MerchantLoginResult
	if err = p.c.Call(ctx, "MerchantLogin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
