// Code generated by Kitex v0.9.1. DO NOT EDIT.

package adminservice

import (
	"context"
	user "delivery-backend/rpc_gen/kitex_gen/user"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"AdminRegister": kitex.NewMethodInfo(
		adminRegisterHandler,
		newAdminRegisterArgs,
		newAdminRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"AdminLogin": kitex.NewMethodInfo(
		adminLoginHandler,
		newAdminLoginArgs,
		newAdminLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	adminServiceServiceInfo                = NewServiceInfo()
	adminServiceServiceInfoForClient       = NewServiceInfoForClient()
	adminServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return adminServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return adminServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return adminServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AdminService"
	handlerType := (*user.AdminService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func adminRegisterHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.AdminRegisterReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.AdminService).AdminRegister(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AdminRegisterArgs:
		success, err := handler.(user.AdminService).AdminRegister(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AdminRegisterResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAdminRegisterArgs() interface{} {
	return &AdminRegisterArgs{}
}

func newAdminRegisterResult() interface{} {
	return &AdminRegisterResult{}
}

type AdminRegisterArgs struct {
	Req *user.AdminRegisterReq
}

func (p *AdminRegisterArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(user.AdminRegisterReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *AdminRegisterArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *AdminRegisterArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *AdminRegisterArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AdminRegisterArgs) Unmarshal(in []byte) error {
	msg := new(user.AdminRegisterReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AdminRegisterArgs_Req_DEFAULT *user.AdminRegisterReq

func (p *AdminRegisterArgs) GetReq() *user.AdminRegisterReq {
	if !p.IsSetReq() {
		return AdminRegisterArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AdminRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdminRegisterArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AdminRegisterResult struct {
	Success *user.AdminRegisterResp
}

var AdminRegisterResult_Success_DEFAULT *user.AdminRegisterResp

func (p *AdminRegisterResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(user.AdminRegisterResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *AdminRegisterResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *AdminRegisterResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *AdminRegisterResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AdminRegisterResult) Unmarshal(in []byte) error {
	msg := new(user.AdminRegisterResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AdminRegisterResult) GetSuccess() *user.AdminRegisterResp {
	if !p.IsSetSuccess() {
		return AdminRegisterResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AdminRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.AdminRegisterResp)
}

func (p *AdminRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdminRegisterResult) GetResult() interface{} {
	return p.Success
}

func adminLoginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.AdminLoginReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.AdminService).AdminLogin(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AdminLoginArgs:
		success, err := handler.(user.AdminService).AdminLogin(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AdminLoginResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAdminLoginArgs() interface{} {
	return &AdminLoginArgs{}
}

func newAdminLoginResult() interface{} {
	return &AdminLoginResult{}
}

type AdminLoginArgs struct {
	Req *user.AdminLoginReq
}

func (p *AdminLoginArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(user.AdminLoginReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *AdminLoginArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *AdminLoginArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *AdminLoginArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AdminLoginArgs) Unmarshal(in []byte) error {
	msg := new(user.AdminLoginReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AdminLoginArgs_Req_DEFAULT *user.AdminLoginReq

func (p *AdminLoginArgs) GetReq() *user.AdminLoginReq {
	if !p.IsSetReq() {
		return AdminLoginArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AdminLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdminLoginArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AdminLoginResult struct {
	Success *user.AdminLoginResp
}

var AdminLoginResult_Success_DEFAULT *user.AdminLoginResp

func (p *AdminLoginResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(user.AdminLoginResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *AdminLoginResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *AdminLoginResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *AdminLoginResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AdminLoginResult) Unmarshal(in []byte) error {
	msg := new(user.AdminLoginResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AdminLoginResult) GetSuccess() *user.AdminLoginResp {
	if !p.IsSetSuccess() {
		return AdminLoginResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AdminLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.AdminLoginResp)
}

func (p *AdminLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdminLoginResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) AdminRegister(ctx context.Context, Req *user.AdminRegisterReq) (r *user.AdminRegisterResp, err error) {
	var _args AdminRegisterArgs
	_args.Req = Req
	var _result AdminRegisterResult
	if err = p.c.Call(ctx, "AdminRegister", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AdminLogin(ctx context.Context, Req *user.AdminLoginReq) (r *user.AdminLoginResp, err error) {
	var _args AdminLoginArgs
	_args.Req = Req
	var _result AdminLoginResult
	if err = p.c.Call(ctx, "AdminLogin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
