// Code generated by Kitex v0.9.1. DO NOT EDIT.

package adminservice

import (
	"context"
	user "delivery-backend/rpc_gen/kitex_gen/user"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AdminRegister(ctx context.Context, Req *user.AdminRegisterReq, callOptions ...callopt.Option) (r *user.AdminRegisterResp, err error)
	AdminLogin(ctx context.Context, Req *user.AdminLoginReq, callOptions ...callopt.Option) (r *user.AdminLoginResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAdminServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAdminServiceClient struct {
	*kClient
}

func (p *kAdminServiceClient) AdminRegister(ctx context.Context, Req *user.AdminRegisterReq, callOptions ...callopt.Option) (r *user.AdminRegisterResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AdminRegister(ctx, Req)
}

func (p *kAdminServiceClient) AdminLogin(ctx context.Context, Req *user.AdminLoginReq, callOptions ...callopt.Option) (r *user.AdminLoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AdminLogin(ctx, Req)
}
