// Code generated by Kitex v0.9.1. DO NOT EDIT.

package merchantservice

import (
	"context"
	user "delivery-backend/rpc_gen/kitex_gen/user"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	MerchantRegister(ctx context.Context, Req *user.MerchantRegisterReq, callOptions ...callopt.Option) (r *user.MerchantRegisterResp, err error)
	MerchantLogin(ctx context.Context, Req *user.MerchantLoginReq, callOptions ...callopt.Option) (r *user.MerchantLoginResp, err error)
	MerchantApply(ctx context.Context, Req *user.MerchantApplyReq, callOptions ...callopt.Option) (r *user.MerchantApplyResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kMerchantServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMerchantServiceClient struct {
	*kClient
}

func (p *kMerchantServiceClient) MerchantRegister(ctx context.Context, Req *user.MerchantRegisterReq, callOptions ...callopt.Option) (r *user.MerchantRegisterResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MerchantRegister(ctx, Req)
}

func (p *kMerchantServiceClient) MerchantLogin(ctx context.Context, Req *user.MerchantLoginReq, callOptions ...callopt.Option) (r *user.MerchantLoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MerchantLogin(ctx, Req)
}

func (p *kMerchantServiceClient) MerchantApply(ctx context.Context, Req *user.MerchantApplyReq, callOptions ...callopt.Option) (r *user.MerchantApplyResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MerchantApply(ctx, Req)
}
