// Code generated by Kitex v0.9.1. DO NOT EDIT.

package merchantservice

import (
	"context"
	user "delivery-backend/rpc_gen/kitex_gen/user"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"MerchantRegister": kitex.NewMethodInfo(
		merchantRegisterHandler,
		newMerchantRegisterArgs,
		newMerchantRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"MerchantLogin": kitex.NewMethodInfo(
		merchantLoginHandler,
		newMerchantLoginArgs,
		newMerchantLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"MerchantApply": kitex.NewMethodInfo(
		merchantApplyHandler,
		newMerchantApplyArgs,
		newMerchantApplyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	merchantServiceServiceInfo                = NewServiceInfo()
	merchantServiceServiceInfoForClient       = NewServiceInfoForClient()
	merchantServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return merchantServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return merchantServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return merchantServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "MerchantService"
	handlerType := (*user.MerchantService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func merchantRegisterHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.MerchantRegisterReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.MerchantService).MerchantRegister(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *MerchantRegisterArgs:
		success, err := handler.(user.MerchantService).MerchantRegister(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*MerchantRegisterResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newMerchantRegisterArgs() interface{} {
	return &MerchantRegisterArgs{}
}

func newMerchantRegisterResult() interface{} {
	return &MerchantRegisterResult{}
}

type MerchantRegisterArgs struct {
	Req *user.MerchantRegisterReq
}

func (p *MerchantRegisterArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(user.MerchantRegisterReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *MerchantRegisterArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *MerchantRegisterArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *MerchantRegisterArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *MerchantRegisterArgs) Unmarshal(in []byte) error {
	msg := new(user.MerchantRegisterReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var MerchantRegisterArgs_Req_DEFAULT *user.MerchantRegisterReq

func (p *MerchantRegisterArgs) GetReq() *user.MerchantRegisterReq {
	if !p.IsSetReq() {
		return MerchantRegisterArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *MerchantRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MerchantRegisterArgs) GetFirstArgument() interface{} {
	return p.Req
}

type MerchantRegisterResult struct {
	Success *user.MerchantRegisterResp
}

var MerchantRegisterResult_Success_DEFAULT *user.MerchantRegisterResp

func (p *MerchantRegisterResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(user.MerchantRegisterResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *MerchantRegisterResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *MerchantRegisterResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *MerchantRegisterResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *MerchantRegisterResult) Unmarshal(in []byte) error {
	msg := new(user.MerchantRegisterResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *MerchantRegisterResult) GetSuccess() *user.MerchantRegisterResp {
	if !p.IsSetSuccess() {
		return MerchantRegisterResult_Success_DEFAULT
	}
	return p.Success
}

func (p *MerchantRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.MerchantRegisterResp)
}

func (p *MerchantRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MerchantRegisterResult) GetResult() interface{} {
	return p.Success
}

func merchantLoginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.MerchantLoginReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.MerchantService).MerchantLogin(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *MerchantLoginArgs:
		success, err := handler.(user.MerchantService).MerchantLogin(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*MerchantLoginResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newMerchantLoginArgs() interface{} {
	return &MerchantLoginArgs{}
}

func newMerchantLoginResult() interface{} {
	return &MerchantLoginResult{}
}

type MerchantLoginArgs struct {
	Req *user.MerchantLoginReq
}

func (p *MerchantLoginArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(user.MerchantLoginReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *MerchantLoginArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *MerchantLoginArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *MerchantLoginArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *MerchantLoginArgs) Unmarshal(in []byte) error {
	msg := new(user.MerchantLoginReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var MerchantLoginArgs_Req_DEFAULT *user.MerchantLoginReq

func (p *MerchantLoginArgs) GetReq() *user.MerchantLoginReq {
	if !p.IsSetReq() {
		return MerchantLoginArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *MerchantLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MerchantLoginArgs) GetFirstArgument() interface{} {
	return p.Req
}

type MerchantLoginResult struct {
	Success *user.MerchantLoginResp
}

var MerchantLoginResult_Success_DEFAULT *user.MerchantLoginResp

func (p *MerchantLoginResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(user.MerchantLoginResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *MerchantLoginResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *MerchantLoginResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *MerchantLoginResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *MerchantLoginResult) Unmarshal(in []byte) error {
	msg := new(user.MerchantLoginResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *MerchantLoginResult) GetSuccess() *user.MerchantLoginResp {
	if !p.IsSetSuccess() {
		return MerchantLoginResult_Success_DEFAULT
	}
	return p.Success
}

func (p *MerchantLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.MerchantLoginResp)
}

func (p *MerchantLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MerchantLoginResult) GetResult() interface{} {
	return p.Success
}

func merchantApplyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(user.MerchantApplyReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(user.MerchantService).MerchantApply(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *MerchantApplyArgs:
		success, err := handler.(user.MerchantService).MerchantApply(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*MerchantApplyResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newMerchantApplyArgs() interface{} {
	return &MerchantApplyArgs{}
}

func newMerchantApplyResult() interface{} {
	return &MerchantApplyResult{}
}

type MerchantApplyArgs struct {
	Req *user.MerchantApplyReq
}

func (p *MerchantApplyArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(user.MerchantApplyReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *MerchantApplyArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *MerchantApplyArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *MerchantApplyArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *MerchantApplyArgs) Unmarshal(in []byte) error {
	msg := new(user.MerchantApplyReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var MerchantApplyArgs_Req_DEFAULT *user.MerchantApplyReq

func (p *MerchantApplyArgs) GetReq() *user.MerchantApplyReq {
	if !p.IsSetReq() {
		return MerchantApplyArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *MerchantApplyArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MerchantApplyArgs) GetFirstArgument() interface{} {
	return p.Req
}

type MerchantApplyResult struct {
	Success *user.MerchantApplyResp
}

var MerchantApplyResult_Success_DEFAULT *user.MerchantApplyResp

func (p *MerchantApplyResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(user.MerchantApplyResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *MerchantApplyResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *MerchantApplyResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *MerchantApplyResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *MerchantApplyResult) Unmarshal(in []byte) error {
	msg := new(user.MerchantApplyResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *MerchantApplyResult) GetSuccess() *user.MerchantApplyResp {
	if !p.IsSetSuccess() {
		return MerchantApplyResult_Success_DEFAULT
	}
	return p.Success
}

func (p *MerchantApplyResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.MerchantApplyResp)
}

func (p *MerchantApplyResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MerchantApplyResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) MerchantRegister(ctx context.Context, Req *user.MerchantRegisterReq) (r *user.MerchantRegisterResp, err error) {
	var _args MerchantRegisterArgs
	_args.Req = Req
	var _result MerchantRegisterResult
	if err = p.c.Call(ctx, "MerchantRegister", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MerchantLogin(ctx context.Context, Req *user.MerchantLoginReq) (r *user.MerchantLoginResp, err error) {
	var _args MerchantLoginArgs
	_args.Req = Req
	var _result MerchantLoginResult
	if err = p.c.Call(ctx, "MerchantLogin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MerchantApply(ctx context.Context, Req *user.MerchantApplyReq) (r *user.MerchantApplyResp, err error) {
	var _args MerchantApplyArgs
	_args.Req = Req
	var _result MerchantApplyResult
	if err = p.c.Call(ctx, "MerchantApply", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
