// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package merchant

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *MerchantLoginReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_MerchantLoginReq[number], err)
}

func (x *MerchantLoginReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Account, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *MerchantLoginReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Password, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *MerchantLoginResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_MerchantLoginResp[number], err)
}

func (x *MerchantLoginResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.UserId, offset, err = fastpb.ReadUint32(buf, _type)
	return offset, err
}

func (x *MerchantRegisterReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_MerchantRegisterReq[number], err)
}

func (x *MerchantRegisterReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Password, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *MerchantRegisterReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.ApplicationId, offset, err = fastpb.ReadUint32(buf, _type)
	return offset, err
}

func (x *MerchantRegisterReq) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.Account, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *MerchantRegisterResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_MerchantRegisterResp[number], err)
}

func (x *MerchantRegisterResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.UserId, offset, err = fastpb.ReadUint32(buf, _type)
	return offset, err
}

func (x *MerchantRegisterResp) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Account, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *MerchantLoginReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *MerchantLoginReq) fastWriteField1(buf []byte) (offset int) {
	if x.Account == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetAccount())
	return offset
}

func (x *MerchantLoginReq) fastWriteField2(buf []byte) (offset int) {
	if x.Password == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetPassword())
	return offset
}

func (x *MerchantLoginResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *MerchantLoginResp) fastWriteField1(buf []byte) (offset int) {
	if x.UserId == 0 {
		return offset
	}
	offset += fastpb.WriteUint32(buf[offset:], 1, x.GetUserId())
	return offset
}

func (x *MerchantRegisterReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *MerchantRegisterReq) fastWriteField1(buf []byte) (offset int) {
	if x.Password == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetPassword())
	return offset
}

func (x *MerchantRegisterReq) fastWriteField2(buf []byte) (offset int) {
	if x.ApplicationId == 0 {
		return offset
	}
	offset += fastpb.WriteUint32(buf[offset:], 2, x.GetApplicationId())
	return offset
}

func (x *MerchantRegisterReq) fastWriteField3(buf []byte) (offset int) {
	if x.Account == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetAccount())
	return offset
}

func (x *MerchantRegisterResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *MerchantRegisterResp) fastWriteField1(buf []byte) (offset int) {
	if x.UserId == 0 {
		return offset
	}
	offset += fastpb.WriteUint32(buf[offset:], 1, x.GetUserId())
	return offset
}

func (x *MerchantRegisterResp) fastWriteField2(buf []byte) (offset int) {
	if x.Account == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetAccount())
	return offset
}

func (x *MerchantLoginReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *MerchantLoginReq) sizeField1() (n int) {
	if x.Account == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetAccount())
	return n
}

func (x *MerchantLoginReq) sizeField2() (n int) {
	if x.Password == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetPassword())
	return n
}

func (x *MerchantLoginResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *MerchantLoginResp) sizeField1() (n int) {
	if x.UserId == 0 {
		return n
	}
	n += fastpb.SizeUint32(1, x.GetUserId())
	return n
}

func (x *MerchantRegisterReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *MerchantRegisterReq) sizeField1() (n int) {
	if x.Password == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetPassword())
	return n
}

func (x *MerchantRegisterReq) sizeField2() (n int) {
	if x.ApplicationId == 0 {
		return n
	}
	n += fastpb.SizeUint32(2, x.GetApplicationId())
	return n
}

func (x *MerchantRegisterReq) sizeField3() (n int) {
	if x.Account == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetAccount())
	return n
}

func (x *MerchantRegisterResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *MerchantRegisterResp) sizeField1() (n int) {
	if x.UserId == 0 {
		return n
	}
	n += fastpb.SizeUint32(1, x.GetUserId())
	return n
}

func (x *MerchantRegisterResp) sizeField2() (n int) {
	if x.Account == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetAccount())
	return n
}

var fieldIDToName_MerchantLoginReq = map[int32]string{
	1: "Account",
	2: "Password",
}

var fieldIDToName_MerchantLoginResp = map[int32]string{
	1: "UserId",
}

var fieldIDToName_MerchantRegisterReq = map[int32]string{
	1: "Password",
	2: "ApplicationId",
	3: "Account",
}

var fieldIDToName_MerchantRegisterResp = map[int32]string{
	1: "UserId",
	2: "Account",
}
